### ISSUE TITLE
。

### ISSUE THREAD

**Issue by TJU-YDragonW** [OpenGVLab/efficient-video-recognition#11]

**Comment by DragonWang-cell** [comment]
For example, this kind of question is very confusing：
TypeError: __init__() takes at least 3 positional arguments (2 given)
Traceback (most recent call last):
  File "/home/wyl/efficient-video-recognition-master/main.py", line 229, in <module>
    if __name__ == '__main__': main()
  File "/home/wyl/efficient-video-recognition-master/main.py", line 141, in main
    for i, (data, labels) in enumerate(train_loader, resume_step):
  File "/home/wyl/miniconda3/envs/FrozenClip/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/wyl/miniconda3/envs/FrozenClip/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/wyl/miniconda3/envs/FrozenClip/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/wyl/miniconda3/envs/FrozenClip/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
  File "av/error.pyx", line 78, in av.error.FFmpegError.__init__
TypeError: __init__() takes at least 3 positional arguments (2 given)
