### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TJU-YDragonW** [OpenGVLab/efficient-video-recognition#6]
Hello！When I run this code, it shows：
AttributeError: 'dict' object has no attribute 'visual'
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    if __name__ == '__main__': main()
  File "main.py", line 114, in main
    num_frames=args.num_frames,
  File "/home/wyl/efficient-video-recognition-master/model.py", line 170, in __init__
    backbone_config = self._create_backbone(backbone_name, backbone_type, backbone_path, backbone_mode)
  File "/home/wyl/efficient-video-recognition-master/model.py", line 202, in _create_backbone
    state_dict = weight_loader_fn(backbone_path)
  File "/home/wyl/efficient-video-recognition-master/weight_loaders.py", line 13, in load_weights_clip
    clip_model = clip_model.visual

Do you konw why？

**Comment by linziyi96** [comment]
Would you mind providing the PyTorch version and the md5sum of the clip checkpoint you are using (by using the command `md5sum /path/to/clip_checkpoint.pt`)? Thanks.

**Comment by TJU-YDragonW** [comment]
Ok，thank you again！
